### ISSUE TITLE
Hyprland is not compatible with aquamarine 0.4.0

### ISSUE THREAD

**Issue by lancelot96** [cpiber/hyprland-ppa#1]
Hyprland: error while loading shared libraries libaquamarine.so.2: cannot open shared object file: No such file or directory

**Comment by cpiber** [comment]
Yeah, say it just now, I will add the old aquamarine, will take a while for it to be available though

**Comment by cpiber** [comment]
The stable version is up on launchpad, I'm currently rebuilding hyprland (stable and unstable) to depend on that version.

If you're impatient, you can manually install it from here: https://launchpad.net/~cppiber/+archive/ubuntu/hyprland/+build/28909645/+files/aquamarine2_0.3.3-1ppa2_amd64.deb if you use plugins you also need the dev version: https://launchpad.net/~cppiber/+archive/ubuntu/hyprland/+build/28909645/+files/aquamarine-stable-dev_0.3.3-1ppa2_amd64.deb. The dev version should replace your current dev version, while the main package lives alongside the other one, since they're ABI-incompatible and thus separate files

**Comment by lancelot96** [comment]
This solves my problem, thanks.
